"""tool_output — fetch the output of a backgrounded tool call.

Reads the output file pointed to by `panel/<tid>.json#output_file`. Default
mode returns the full accumulated output; `delta=true` returns only the bytes
added since the last fetch (tracked via `last_delivered_bytes` on the panel
entry, which is the same field progress-heartbeats advance).

Security: `task_id` is pattern-validated and the resolved `output_file` is
checked to stay under `tool_results_dir`. A crafted entry that sets
`output_file` to `/etc/passwd` is rejected before any read.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from butterfly.session_engine.panel import load_entry, save_entry

# Tids generated by `new_tid` look like "bg_<hex>" with optional future
# prefixes (e.g. "sa_" for sub-agents). Keep the charset tight so nothing
# resembling a path separator, `..`, or absolute path can sneak through.
_TID_RE = re.compile(r"^[a-zA-Z]{1,8}_[a-z0-9]{4,32}$")


def _is_within(path: Path, base: Path) -> bool:
    """Return True iff `path` is inside `base` (both resolved)."""
    try:
        path.resolve().relative_to(base.resolve())
        return True
    except (ValueError, OSError):
        return False


class ToolOutputExecutor:
    """Fetch output of a background task by tid. Context-injected with panel_dir
    and tool_results_dir (output files must live under tool_results_dir)."""

    def __init__(
        self,
        panel_dir: Path | None = None,
        tool_results_dir: Path | None = None,
    ) -> None:
        self._panel_dir = panel_dir
        self._tool_results_dir = tool_results_dir

    async def execute(self, **kwargs: Any) -> str:
        task_id = kwargs.get("task_id")
        if not task_id or not isinstance(task_id, str):
            return "Error: task_id is required."
        if not _TID_RE.match(task_id):
            return (
                f"Error: invalid task_id '{task_id}'. Expected '<prefix>_<hex>', "
                "letters/digits/underscore only."
            )
        if self._panel_dir is None:
            return "Error: tool_output is not wired to a session panel directory."

        entry = load_entry(self._panel_dir, task_id)
        if entry is None:
            return f"Error: no panel entry with task_id '{task_id}'."

        delta_mode = bool(kwargs.get("delta", False))

        if not entry.output_file:
            return f"Task {task_id} has no output file yet. Status: {entry.status}."

        output_path = Path(entry.output_file)
        # Prevent a crafted/corrupt entry from pointing at an arbitrary file.
        if self._tool_results_dir is not None and not _is_within(
            output_path, self._tool_results_dir
        ):
            return (
                f"Error: output_file for {task_id} is outside the session "
                "tool_results directory; refusing to read."
            )
        if not output_path.exists():
            return f"Task {task_id} output file is missing ({output_path}). Status: {entry.status}."

        try:
            data = output_path.read_bytes()
        except OSError as exc:
            return f"Error reading output file for {task_id}: {exc}"

        if delta_mode:
            start = entry.last_delivered_bytes
            chunk = data[start:]
            entry.last_delivered_bytes = len(data)
            save_entry(self._panel_dir, entry)
            text = chunk.decode(errors="replace")
        else:
            text = data.decode(errors="replace")

        footer = (
            f"\n[task {task_id} status={entry.status} exit={entry.exit_code} "
            f"bytes={entry.output_bytes}"
            + (" delta-mode" if delta_mode else "")
            + "]"
        )
        return (text.rstrip() + footer) if text else footer.lstrip()
